name: Test Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [ubuntu-24.04-arm, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Hatch
        run: pipx install hatch
      - name: Run tests
        run: hatch test --all
